Watching for file changes with StatReloader
[28/Oct/2019 03:35:38] "GET / HTTP/1.1" 200 5584
[28/Oct/2019 03:35:46] "GET / HTTP/1.1" 200 5584
Watching for file changes with StatReloader
[28/Oct/2019 03:37:00] "GET / HTTP/1.1" 200 5584
[28/Oct/2019 03:37:05] "GET / HTTP/1.1" 200 5584
[28/Oct/2019 03:37:13] "GET /movies/ HTTP/1.1" 200 39682
[28/Oct/2019 03:41:06] "GET /movies/ HTTP/1.1" 200 39682
[28/Oct/2019 03:41:06] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
[28/Oct/2019 03:41:06] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
[28/Oct/2019 03:41:06] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
[28/Oct/2019 03:41:06] "GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
[28/Oct/2019 03:41:06] "GET /static/rest_framework/js/jquery-3.4.1.min.js HTTP/1.1" 304 0
[28/Oct/2019 03:41:06] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[28/Oct/2019 03:41:06] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[28/Oct/2019 03:41:06] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[28/Oct/2019 03:41:07] "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[28/Oct/2019 03:41:07] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
Not Found: /theater
[28/Oct/2019 03:41:14] "GET /theater HTTP/1.1" 404 6640
[28/Oct/2019 03:41:16] "GET /theaters/ HTTP/1.1" 200 98354
[28/Oct/2019 03:41:16] "GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
[28/Oct/2019 03:41:54] "GET /theaters/ HTTP/1.1" 200 98354
[28/Oct/2019 05:06:06] "GET / HTTP/1.1" 200 159
[28/Oct/2019 07:24:29] "GET /theaters/ HTTP/1.1" 200 98354
[28/Oct/2019 07:24:29] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
[28/Oct/2019 07:24:29] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
[28/Oct/2019 07:24:29] "GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
[28/Oct/2019 07:24:29] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
[28/Oct/2019 07:24:29] "GET /static/rest_framework/js/jquery-3.4.1.min.js HTTP/1.1" 304 0
[28/Oct/2019 07:24:29] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[28/Oct/2019 07:24:29] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[28/Oct/2019 07:24:29] "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[28/Oct/2019 07:24:29] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[28/Oct/2019 07:24:29] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[28/Oct/2019 07:24:29] "GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
[28/Oct/2019 07:24:33] "GET / HTTP/1.1" 200 5584
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[28/Oct/2019 08:52:09] "GET / HTTP/1.1" 200 5584
[28/Oct/2019 08:52:09] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385
[28/Oct/2019 08:52:09] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
[28/Oct/2019 08:52:09] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
[28/Oct/2019 08:52:09] "GET /static/rest_framework/css/default.css HTTP/1.1" 200 1131
[28/Oct/2019 08:52:09] "GET /static/rest_framework/js/jquery-3.4.1.min.js HTTP/1.1" 200 88145
[28/Oct/2019 08:52:09] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 37608
[28/Oct/2019 08:52:09] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
[28/Oct/2019 08:52:09] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1719
[28/Oct/2019 08:52:09] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3597
[28/Oct/2019 08:52:09] "GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268
[28/Oct/2019 08:52:09] "GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
Not Found: /favicon.ico
[28/Oct/2019 08:52:09] "GET /favicon.ico HTTP/1.1" 404 6652
[28/Oct/2019 08:52:20] "GET / HTTP/1.1" 200 159
[28/Oct/2019 09:59:56] code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x00\x8c\x01\x00\x00\x88\x03\x03Ôw³æÿñeð©ÁDôF\x8f«Æ£ßÉ©\xadµ§òù\x9c\x7f}ÛO\x04ç\x00\x00\x1aÀ/À+À\x11À\x07À\x13À')
[28/Oct/2019 09:59:56] You're accessing the development server over HTTPS, but it only supports HTTP.

[28/Oct/2019 11:53:08] "GET / HTTP/1.1" 200 5584
[28/Oct/2019 11:53:09] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385
[28/Oct/2019 11:53:09] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
[28/Oct/2019 11:53:09] "GET /static/rest_framework/css/default.css HTTP/1.1" 200 1131
[28/Oct/2019 11:53:09] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3597
[28/Oct/2019 11:53:09] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
[28/Oct/2019 11:53:09] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1719
[28/Oct/2019 11:53:09] "GET /static/rest_framework/js/jquery-3.4.1.min.js HTTP/1.1" 200 88145
[28/Oct/2019 11:53:09] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 37608
[28/Oct/2019 11:53:09] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
[28/Oct/2019 11:53:09] "GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268
[28/Oct/2019 11:53:09] "GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
Not Found: /favicon.ico
[28/Oct/2019 11:53:09] "GET /favicon.ico HTTP/1.1" 404 6652
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[28/Oct/2019 12:09:35] "GET / HTTP/1.1" 200 5584
[28/Oct/2019 12:09:36] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
[28/Oct/2019 12:09:36] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
[28/Oct/2019 12:09:36] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
[28/Oct/2019 12:09:36] "GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
[28/Oct/2019 12:09:36] "GET /static/rest_framework/js/jquery-3.4.1.min.js HTTP/1.1" 304 0
[28/Oct/2019 12:09:36] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[28/Oct/2019 12:09:36] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[28/Oct/2019 12:09:36] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[28/Oct/2019 12:09:36] "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[28/Oct/2019 12:09:36] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[28/Oct/2019 12:09:36] "GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
Not Found: /favicon.ico
[28/Oct/2019 12:09:36] "GET /favicon.ico HTTP/1.1" 404 6652
[28/Oct/2019 12:09:41] "GET /movies/ HTTP/1.1" 200 39682
[28/Oct/2019 12:10:44] "GET /movies/ HTTP/1.1" 200 39682
[28/Oct/2019 12:10:49] "GET /theaters/ HTTP/1.1" 200 98354
Not Found: /movieschedule
[28/Oct/2019 12:11:06] "GET /movieschedule HTTP/1.1" 404 6658
[28/Oct/2019 12:11:09] "GET /movieschedules HTTP/1.1" 301 0
[28/Oct/2019 12:11:11] "GET /movieschedules/ HTTP/1.1" 200 1746027
[28/Oct/2019 12:11:18] "GET /theaters/ HTTP/1.1" 200 98354
Internal Server Error: /movie_api/searchTheaterWithMoviePos/
Traceback (most recent call last):
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/movieapi.py", line 140, in SearchTheaterWithMoviePos
    MovieCrawl(reqtheater)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/crawling.py", line 43, in MovieCrawl
    MegaBoxCrawl(theaterObj)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/crawling.py", line 295, in MegaBoxCrawl
    driver.get(url)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: headless chrome=78.0.3904.70)

[28/Oct/2019 12:16:29] "GET /movie_api/searchTheaterWithMoviePos/?latitude=37.498241&longitude=127.026451&movieName=%EC%A1%B0%EC%BB%A4 HTTP/1.1" 500 95559
Internal Server Error: /movie_api/searchTheaterWithMoviePos/
Traceback (most recent call last):
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/movieapi.py", line 140, in SearchTheaterWithMoviePos
    MovieCrawl(reqtheater)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/crawling.py", line 43, in MovieCrawl
    MegaBoxCrawl(theaterObj)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/crawling.py", line 295, in MegaBoxCrawl
    driver.get(url)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: headless chrome=78.0.3904.70)

[28/Oct/2019 12:16:37] "GET /movie_api/searchTheaterWithMoviePos/?latitude=37.498241&longitude=127.026451&movieName=%EC%A1%B0%EC%BB%A4 HTTP/1.1" 500 95559
[28/Oct/2019 12:16:42] "GET /theaters/ HTTP/1.1" 200 98354
[28/Oct/2019 12:16:48] "GET /movieschedules/ HTTP/1.1" 200 1741267
Internal Server Error: /movie_api/searchTheaterWithMoviePos/
Traceback (most recent call last):
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/movieapi.py", line 140, in SearchTheaterWithMoviePos
    MovieCrawl(reqtheater)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/crawling.py", line 43, in MovieCrawl
    MegaBoxCrawl(theaterObj)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/crawling.py", line 295, in MegaBoxCrawl
    driver.get(url)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: headless chrome=78.0.3904.70)

[28/Oct/2019 12:17:11] "GET /movie_api/searchTheaterWithMoviePos/?latitude=37.498241&longitude=127.026451&movieName=%EC%A1%B0%EC%BB%A4 HTTP/1.1" 500 96528
Internal Server Error: /movie_api/searchCGVMovie/
Traceback (most recent call last):
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/movieapi_test.py", line 43, in SearchCGVMovie
    movieList = CGVCrawl(reqtheater)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/crawling.py", line 64, in CGVCrawl
    driver.get(url)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: headless chrome=78.0.3904.70)

[28/Oct/2019 12:17:27] "GET /movie_api/searchCGVMovie/ HTTP/1.1" 500 83867
Internal Server Error: /movie_api/searchCGVMovie/
Traceback (most recent call last):
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/movieapi_test.py", line 43, in SearchCGVMovie
    movieList = CGVCrawl(reqtheater)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/crawling.py", line 64, in CGVCrawl
    driver.get(url)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: headless chrome=78.0.3904.70)

[28/Oct/2019 12:17:28] "GET /movie_api/searchCGVMovie/ HTTP/1.1" 500 83867
Internal Server Error: /movie_api/searchCGVMovie/
Traceback (most recent call last):
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/movieapi_test.py", line 43, in SearchCGVMovie
    movieList = CGVCrawl(reqtheater)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/crawling.py", line 64, in CGVCrawl
    driver.get(url)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: headless chrome=78.0.3904.70)

[28/Oct/2019 12:17:32] "GET /movie_api/searchCGVMovie/ HTTP/1.1" 500 83867
Internal Server Error: /movie_api/searchCGVMovie/
Traceback (most recent call last):
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/movieapi_test.py", line 43, in SearchCGVMovie
    movieList = CGVCrawl(reqtheater)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/crawling.py", line 64, in CGVCrawl
    driver.get(url)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: headless chrome=78.0.3904.70)

[28/Oct/2019 12:17:34] "GET /movie_api/searchCGVMovie/ HTTP/1.1" 500 83867
Internal Server Error: /movie_api/searchCGVMovie/
Traceback (most recent call last):
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/movieapi_test.py", line 43, in SearchCGVMovie
    movieList = CGVCrawl(reqtheater)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/crawling.py", line 64, in CGVCrawl
    driver.get(url)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: headless chrome=78.0.3904.70)

[28/Oct/2019 12:17:41] "GET /movie_api/searchCGVMovie/ HTTP/1.1" 500 83867
[28/Oct/2019 12:17:48] "GET /movieschedules/ HTTP/1.1" 200 1740192
[28/Oct/2019 12:17:51] "GET /movieschedules/ HTTP/1.1" 200 1740192
Watching for file changes with StatReloader
[28/Oct/2019 13:27:26] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
[28/Oct/2019 13:27:26] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
[28/Oct/2019 13:27:26] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
[28/Oct/2019 13:27:26] "GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
[28/Oct/2019 13:27:26] "GET /theaters/ HTTP/1.1" 200 98368
[28/Oct/2019 13:27:26] "GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
[28/Oct/2019 13:27:26] "GET /static/rest_framework/js/jquery-3.4.1.min.js HTTP/1.1" 304 0
[28/Oct/2019 13:27:26] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[28/Oct/2019 13:27:26] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[28/Oct/2019 13:27:26] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[28/Oct/2019 13:27:26] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[28/Oct/2019 13:27:26] "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[28/Oct/2019 13:28:04] "GET /movieschedules/ HTTP/1.1" 200 1850948
[28/Oct/2019 13:37:28] "GET / HTTP/1.1" 200 5584
[28/Oct/2019 13:37:42] "GET /theaters/ HTTP/1.1" 200 98368
Internal Server Error: /movie_api/searchTheaterOrderedScheduleWithPos/
Traceback (most recent call last):
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/movieapi.py", line 90, in SearchTheaterOrderedScheduleWithPos
    MovieCrawl(reqtheater)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/crawling.py", line 45, in MovieCrawl
    LotteCinemaCrawl(theaterObj)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/crawling.py", line 186, in LotteCinemaCrawl
    driver.get(url)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: headless chrome=78.0.3904.70)

[28/Oct/2019 13:39:30] "GET /movie_api/searchTheaterOrderedScheduleWithPos/?longitude=127.029248&latitude=37.511168&movieName=%EA%B0%80%EC%9E%A5+%EB%B3%B4%ED%86%B5%EC%9D%98+%EC%97%B0%EC%95%A0 HTTP/1.1" 500 96405
Internal Server Error: /movie_api/searchTheaterOrderedScheduleWithPos/
Traceback (most recent call last):
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/movieapi.py", line 90, in SearchTheaterOrderedScheduleWithPos
    MovieCrawl(reqtheater)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/crawling.py", line 45, in MovieCrawl
    LotteCinemaCrawl(theaterObj)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/crawling.py", line 186, in LotteCinemaCrawl
    driver.get(url)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: headless chrome=78.0.3904.70)

[28/Oct/2019 13:40:39] "GET /movie_api/searchTheaterOrderedScheduleWithPos/?longitude=127.029248&latitude=37.511168&movieName=%EA%B0%80%EC%9E%A5+%EB%B3%B4%ED%86%B5%EC%9D%98+%EC%97%B0%EC%95%A0 HTTP/1.1" 500 96404
Internal Server Error: /movie_api/searchCGVMovie/
Traceback (most recent call last):
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/movieapi_test.py", line 43, in SearchCGVMovie
    movieList = CGVCrawl(reqtheater)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/crawling.py", line 64, in CGVCrawl
    driver.get(url)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: headless chrome=78.0.3904.70)

[28/Oct/2019 13:41:50] "GET /movie_api/searchCGVMovie/ HTTP/1.1" 500 83916
Internal Server Error: /movie_api/searchCGVMovie/
Traceback (most recent call last):
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/movieapi_test.py", line 43, in SearchCGVMovie
    movieList = CGVCrawl(reqtheater)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/crawling.py", line 64, in CGVCrawl
    driver.get(url)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: headless chrome=78.0.3904.70)

[28/Oct/2019 13:41:54] "GET /movie_api/searchCGVMovie/ HTTP/1.1" 500 83916
/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/crawling.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
October 28, 2019 - 13:18:57
Django version 2.2.6, using settings 'movie_server.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
long:37.511168, lat:127.029248, movieName:가장 보통의 연애
lottecinema브로드웨이(신사)
long:37.511168, lat:127.029248, movieName:가장 보통의 연애
lottecinema브로드웨이(신사)
cgv강남
cgv강남
Watching for file changes with StatReloader
/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/crawling.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
October 28, 2019 - 13:46:07
Django version 2.2.6, using settings 'movie_server.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
cgv강남
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
cgv강변
말레피센트 2
82년생 김지영
조커
아이다호
스탠 바이 미
경계선
람보: 라스트 워
시크릿 슈퍼스타
퍼펙트 스트레인저
스노우 화이트
빅트립: 아기팬더 배달 대모험
나쁜 녀석들: 더 무비
cgv건대입구
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
cgv구로
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
아이다호
스탠 바이 미
경계선
람보: 라스트 워
시크릿 슈퍼스타
퍼펙트 스트레인저
스노우 화이트
빅트립: 아기팬더 배달 대모험
cgv대학로
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
아이다호
스탠 바이 미
경계선
람보: 라스트 워
시크릿 슈퍼스타
블러드 심플
cgv동대문
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
빅트립: 아기팬더 배달 대모험
cgv등촌
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
시크릿 슈퍼스타
빅트립: 아기팬더 배달 대모험
두번할까요
북간도의 십자가
체크 히어로
cgv명동
말레피센트 2
82년생 김지영
조커
cgv명동역 씨네라이브러리
말레피센트 2
82년생 김지영
조커
아이다호
스탠 바이 미
경계선
시크릿 슈퍼스타
이다혜의 북클럽 시즌2:호밀밭의 파수꾼
이다혜의 북클럽 시즌2:호밀밭의 파수꾼
해당 영화를 찾을 수 없습니다. Naver Movie API
퍼펙트 스트레인저
신문기자
판소리 복서
cgv목동
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
시크릿 슈퍼스타
빅트립: 아기팬더 배달 대모험
두번할까요
cgv미아
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
cgv불광
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
시크릿 슈퍼스타
퍼펙트맨
퍼펙트 스트레인저
빅트립: 아기팬더 배달 대모험
cgv상봉
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
시크릿 슈퍼스타
나쁜 녀석들: 더 무비
cgv성신여대입구
말레피센트 2
82년생 김지영
조커
cgv송파
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
빅트립: 아기팬더 배달 대모험
두번할까요
cgv수유
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
퍼펙트 스트레인저
나쁜 녀석들: 더 무비
cgv신촌아트레온
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
아이다호
스탠 바이 미
경계선
람보: 라스트 워
시크릿 슈퍼스타
퍼펙트 스트레인저
블러드 심플
스노우 화이트
cgv압구정
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
아이다호
스탠 바이 미
경계선
메기
퍼펙트 스트레인저
Watching for file changes with StatReloader
/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/crawling.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
October 28, 2019 - 13:48:04
Django version 2.2.6, using settings 'movie_server.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/crawling.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
October 28, 2019 - 13:48:24
Django version 2.2.6, using settings 'movie_server.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
cgv강남
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
cgv강변
말레피센트 2
82년생 김지영
조커
아이다호
스탠 바이 미
경계선
람보: 라스트 워
시크릿 슈퍼스타
퍼펙트 스트레인저
스노우 화이트
빅트립: 아기팬더 배달 대모험
나쁜 녀석들: 더 무비
cgv건대입구
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
cgv구로
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
아이다호
스탠 바이 미
경계선
람보: 라스트 워
시크릿 슈퍼스타
퍼펙트 스트레인저
스노우 화이트
빅트립: 아기팬더 배달 대모험
cgv대학로
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
아이다호
스탠 바이 미
경계선
람보: 라스트 워
시크릿 슈퍼스타
블러드 심플
cgv동대문
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
빅트립: 아기팬더 배달 대모험
cgv등촌
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
시크릿 슈퍼스타
빅트립: 아기팬더 배달 대모험
두번할까요
북간도의 십자가
체크 히어로
cgv명동
말레피센트 2
82년생 김지영
조커
cgv명동역 씨네라이브러리
말레피센트 2
82년생 김지영
조커
아이다호
스탠 바이 미
경계선
시크릿 슈퍼스타
이다혜의 북클럽 시즌2:호밀밭의 파수꾼
이다혜의 북클럽 시즌2:호밀밭의 파수꾼
해당 영화를 찾을 수 없습니다. Naver Movie API
퍼펙트 스트레인저
신문기자
판소리 복서
cgv목동
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
시크릿 슈퍼스타
빅트립: 아기팬더 배달 대모험
두번할까요
cgv미아
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
cgv불광
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
시크릿 슈퍼스타
퍼펙트맨
퍼펙트 스트레인저
빅트립: 아기팬더 배달 대모험
cgv상봉
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
시크릿 슈퍼스타
나쁜 녀석들: 더 무비
cgv성신여대입구
말레피센트 2
82년생 김지영
조커
cgv송파
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
빅트립: 아기팬더 배달 대모험
두번할까요
cgv수유
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
퍼펙트 스트레인저
나쁜 녀석들: 더 무비
cgv신촌아트레온
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
아이다호
스탠 바이 미
경계선
람보: 라스트 워
시크릿 슈퍼스타
퍼펙트 스트레인저
블러드 심플
스노우 화이트
cgv압구정
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
아이다호
스탠 바이 미
경계선
메기
퍼펙트 스트레인저
블러드 심플
와일드 로즈
신문기자
미드소마 감독판
미드소마 감독판
해당 영화를 찾을 수 없습니다. Naver Movie API
판소리 복서
벌새
원스 어폰 어 타임... 인 할리우드
cgv여의도
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
아이다호
스탠 바이 미
경계선
람보: 라스트 워
시크릿 슈퍼스타
메기
퍼펙트 스트레인저
cgv영등포
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
시크릿 슈퍼스타
터미네이터2
퍼펙트 스트레인저
스노우 화이트
두번할까요
cgv왕십리
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
시크릿 슈퍼스타
퍼펙트 스트레인저
스노우 화이트
나쁜 녀석들: 더 무비
cgv용산아이파크몰
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
아이다호
스탠 바이 미
경계선
람보: 라스트 워
시크릿 슈퍼스타
터미네이터2
퍼펙트 스트레인저
블러드 심플
스노우 화이트
빅트립: 아기팬더 배달 대모험
체크 히어로
cgv중계
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
시크릿 슈퍼스타
빅트립: 아기팬더 배달 대모험
나쁜 녀석들: 더 무비
cgv천호
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
퍼펙트맨
두번할까요
cgv청담씨네시티
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
cgv피카디리1958
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
cgv하계
말레피센트 2
82년생 김지영
조커
빅트립: 아기팬더 배달 대모험
체크 히어로
cgv홍대
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
cgv경기광주
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
체크 히어로
cgv광교상현
82년생 김지영
조커
시크릿 슈퍼스타
터미네이터2
퍼펙트 스트레인저
스노우 화이트
빅트립: 아기팬더 배달 대모험
cgv광명철산
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
퍼펙트맨
cgv구리
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
시크릿 슈퍼스타
cgv김포
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
cgv김포운양
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
빅트립: 아기팬더 배달 대모험
cgv김포풍무
82년생 김지영
조커
빅트립: 아기팬더 배달 대모험
체크 히어로
cgv김포한강
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
시크릿 슈퍼스타
빅트립: 아기팬더 배달 대모험
두번할까요
cgv동백
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
퍼펙트맨
퍼펙트 스트레인저
빅트립: 아기팬더 배달 대모험
체크 히어로
cgv동수원
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
시크릿 슈퍼스타
cgv동탄
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
빅트립: 아기팬더 배달 대모험
체크 히어로
cgv동탄역
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
빅트립: 아기팬더 배달 대모험
cgv배곧
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
빅트립: 아기팬더 배달 대모험
cgv범계
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
퍼펙트맨
빅트립: 아기팬더 배달 대모험
cgv부천
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
시크릿 슈퍼스타
와일드 로즈
cgv부천역
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
시크릿 슈퍼스타
퍼펙트 스트레인저
cgv북수원
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
체크 히어로
cgv산본
말레피센트 2
82년생 김지영
Watching for file changes with StatReloader
/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/crawling.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
October 28, 2019 - 13:51:07
Django version 2.2.6, using settings 'movie_server.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/movieapi_test.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
October 28, 2019 - 13:52:21
Django version 2.2.6, using settings 'movie_server.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/crawling.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
October 28, 2019 - 13:53:11
Django version 2.2.6, using settings 'movie_server.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/movieapi.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
October 28, 2019 - 13:53:15
Django version 2.2.6, using settings 'movie_server.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
October 28, 2019 - 13:53:22
Django version 2.2.6, using settings 'movie_server.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
cgv강남
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
cgv강변
말레피센트 2
82년생 김지영
조커
아이다호
스탠 바이 미
경계선
람보: 라스트 워
시크릿 슈퍼스타
퍼펙트 스트레인저
스노우 화이트
빅트립: 아기팬더 배달 대모험
나쁜 녀석들: 더 무비
cgv건대입구
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
cgv구로
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
아이다호
스탠 바이 미
경계선
람보: 라스트 워
시크릿 슈퍼스타
퍼펙트 스트레인저
스노우 화이트
빅트립: 아기팬더 배달 대모험
cgv대학로
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
아이다호
스탠 바이 미
경계선
람보: 라스트 워
시크릿 슈퍼스타
블러드 심플
cgv동대문
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
빅트립: 아기팬더 배달 대모험
cgv등촌
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
시크릿 슈퍼스타
빅트립: 아기팬더 배달 대모험
두번할까요
북간도의 십자가
체크 히어로
cgv명동
말레피센트 2
82년생 김지영
조커
cgv명동역 씨네라이브러리
말레피센트 2
82년생 김지영
조커
아이다호
스탠 바이 미
경계선
시크릿 슈퍼스타
이다혜의 북클럽 시즌2:호밀밭의 파수꾼
이다혜의 북클럽 시즌2:호밀밭의 파수꾼
해당 영화를 찾을 수 없습니다. Naver Movie API
퍼펙트 스트레인저
신문기자
판소리 복서
cgv목동
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
시크릿 슈퍼스타
빅트립: 아기팬더 배달 대모험
두번할까요
cgv미아
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
cgv불광
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
시크릿 슈퍼스타
퍼펙트맨
퍼펙트 스트레인저
빅트립: 아기팬더 배달 대모험
cgv상봉
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
시크릿 슈퍼스타
나쁜 녀석들: 더 무비
cgv성신여대입구
말레피센트 2
82년생 김지영
조커
cgv송파
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
빅트립: 아기팬더 배달 대모험
두번할까요
cgv수유
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
퍼펙트 스트레인저
나쁜 녀석들: 더 무비
cgv신촌아트레온
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
아이다호
스탠 바이 미
경계선
람보: 라스트 워
시크릿 슈퍼스타
퍼펙트 스트레인저
블러드 심플
스노우 화이트
cgv압구정
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
아이다호
스탠 바이 미
경계선
메기
퍼펙트 스트레인저
블러드 심플
와일드 로즈
신문기자
미드소마 감독판
미드소마 감독판
해당 영화를 찾을 수 없습니다. Naver Movie API
판소리 복서
벌새
원스 어폰 어 타임... 인 할리우드
cgv여의도
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
아이다호
스탠 바이 미
경계선
람보: 라스트 워
시크릿 슈퍼스타
메기
퍼펙트 스트레인저
cgv영등포
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
시크릿 슈퍼스타
터미네이터2
퍼펙트 스트레인저
스노우 화이트
두번할까요
cgv왕십리
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
시크릿 슈퍼스타
퍼펙트 스트레인저
스노우 화이트
나쁜 녀석들: 더 무비
cgv용산아이파크몰
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
아이다호
스탠 바이 미
경계선
람보: 라스트 워
시크릿 슈퍼스타
터미네이터2
퍼펙트 스트레인저
블러드 심플
스노우 화이트
빅트립: 아기팬더 배달 대모험
체크 히어로
cgv중계
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
시크릿 슈퍼스타
빅트립: 아기팬더 배달 대모험
나쁜 녀석들: 더 무비
cgv천호
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
퍼펙트맨
두번할까요
cgv청담씨네시티
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
cgv피카디리1958
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
cgv하계
말레피센트 2
82년생 김지영
조커
빅트립: 아기팬더 배달 대모험
체크 히어로
cgv홍대
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
cgv경기광주
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
체크 히어로
cgv광교상현
82년생 김지영
조커
시크릿 슈퍼스타
터미네이터2
퍼펙트 스트레인저
스노우 화이트
빅트립: 아기팬더 배달 대모험
cgv광명철산
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
퍼펙트맨
cgv구리
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
시크릿 슈퍼스타
cgv김포
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
cgv김포운양
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
빅트립: 아기팬더 배달 대모험
cgv김포풍무
82년생 김지영
조커
빅트립: 아기팬더 배달 대모험
체크 히어로
cgv김포한강
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
시크릿 슈퍼스타
빅트립: 아기팬더 배달 대모험
두번할까요
cgv동백
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
퍼펙트맨
퍼펙트 스트레인저
빅트립: 아기팬더 배달 대모험
체크 히어로
cgv동수원
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
시크릿 슈퍼스타
cgv동탄
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
빅트립: 아기팬더 배달 대모험
체크 히어로
cgv동탄역
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
빅트립: 아기팬더 배달 대모험
cgv배곧
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
빅트립: 아기팬더 배달 대모험
cgv범계
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
퍼펙트맨
빅트립: 아기팬더 배달 대모험
cgv부천
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
시크릿 슈퍼스타
와일드 로즈
cgv부천역
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
시크릿 슈퍼스타
퍼펙트 스트레인저
cgv북수원
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
체크 히어로
cgv산본
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워
cgv서현
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
cgv소풍
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
아이다호
스탠 바이 미
경계선
람보: 라스트 워
시크릿 슈퍼스타
퍼펙트 스트레인저
블러드 심플
빅트립: 아기팬더 배달 대모험
두번할까요
체크 히어로
몬스터 하우스
cgv수원
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
cgv스타필드시티위례
말레피센트 2
82년생 김지영
조커
가장 보통의 연애
람보: 라스트 워[28/Oct/2019 13:57:16] "GET /movie_api/searchCGVMovie/ HTTP/1.1" 200 431263
[28/Oct/2019 14:02:34] "GET /movie_api/searchTimeOrderedScheduleWithPos/?longitude=127.029248&latitude=37.511168 HTTP/1.1" 200 93762
Internal Server Error: /movie_api/searchMovieListWithPos/
Traceback (most recent call last):
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/movieapi.py", line 213, in SearchMovieListWithPos
    MovieCrawl(reqtheater)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/crawling.py", line 47, in MovieCrawl
    LotteCinemaCrawl(theaterObj)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/crawling.py", line 189, in LotteCinemaCrawl
    driver.get(url)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: headless chrome=78.0.3904.70)

[28/Oct/2019 14:16:41] "GET /movie_api/searchMovieListWithPos/?longitude=127.029248&latitude=37.511168 HTTP/1.1" 500 95191
Internal Server Error: /movie_api/searchMovieListWithPos/
Traceback (most recent call last):
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/movieapi.py", line 213, in SearchMovieListWithPos
    MovieCrawl(reqtheater)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/crawling.py", line 47, in MovieCrawl
    LotteCinemaCrawl(theaterObj)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/crawling.py", line 189, in LotteCinemaCrawl
    driver.get(url)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: headless chrome=78.0.3904.70)

[28/Oct/2019 14:17:33] "GET /movie_api/searchMovieListWithPos/?longitude=127.029248&latitude=37.511168 HTTP/1.1" 500 95190
Internal Server Error: /movie_api/searchMovieListWithPos/
Traceback (most recent call last):
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/movieapi.py", line 213, in SearchMovieListWithPos
    MovieCrawl(reqtheater)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/crawling.py", line 47, in MovieCrawl
    LotteCinemaCrawl(theaterObj)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/crawling.py", line 189, in LotteCinemaCrawl
    driver.get(url)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: headless chrome=78.0.3904.70)

[28/Oct/2019 14:17:56] "GET /movie_api/searchMovieListWithPos/?longitude=127.029248&latitude=37.511168 HTTP/1.1" 500 95190
Internal Server Error: /movie_api/searchMovieListWithPos/
Traceback (most recent call last):
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/movieapi.py", line 213, in SearchMovieListWithPos
    MovieCrawl(reqtheater)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/crawling.py", line 47, in MovieCrawl
    LotteCinemaCrawl(theaterObj)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/crawling.py", line 189, in LotteCinemaCrawl
    driver.get(url)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: headless chrome=78.0.3904.70)

[28/Oct/2019 14:17:59] "GET /movie_api/searchMovieListWithPos/?longitude=127.029248&latitude=37.511168 HTTP/1.1" 500 95190
[28/Oct/2019 14:21:27] "GET / HTTP/1.1" 200 5584
[28/Oct/2019 14:21:37] "GET /movies/ HTTP/1.1" 200 43877
[28/Oct/2019 14:22:20] "GET /theaters/ HTTP/1.1" 200 98368
Internal Server Error: /movie_api/searchMovieListWithPos/
Traceback (most recent call last):
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/movieapi.py", line 213, in SearchMovieListWithPos
    MovieCrawl(reqtheater)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/crawling.py", line 47, in MovieCrawl
    LotteCinemaCrawl(theaterObj)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/crawling.py", line 189, in LotteCinemaCrawl
    driver.get(url)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: headless chrome=78.0.3904.70)

[28/Oct/2019 14:27:30] "GET /movie_api/searchMovieListWithPos/?longitude=127.029248&latitude=37.511168 HTTP/1.1" 500 95191
Internal Server Error: /movie_api/searchMovieListWithPos/
Traceback (most recent call last):
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/movieapi.py", line 213, in SearchMovieListWithPos
    MovieCrawl(reqtheater)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/crawling.py", line 47, in MovieCrawl
    LotteCinemaCrawl(theaterObj)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/crawling.py", line 189, in LotteCinemaCrawl
    driver.get(url)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: headless chrome=78.0.3904.70)

[28/Oct/2019 14:27:38] "GET /movie_api/searchMovieListWithPos/?longitude=127.029248&latitude=37.511168 HTTP/1.1" 500 95192
Internal Server Error: /movie_api/searchMovieListWithPos/
Traceback (most recent call last):
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/movieapi.py", line 213, in SearchMovieListWithPos
    MovieCrawl(reqtheater)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/crawling.py", line 47, in MovieCrawl
    LotteCinemaCrawl(theaterObj)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/crawling.py", line 189, in LotteCinemaCrawl
    driver.get(url)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: headless chrome=78.0.3904.70)

[28/Oct/2019 14:32:18] "GET /movie_api/searchMovieListWithPos/?longitude=127.029248&latitude=37.511168 HTTP/1.1" 500 95190
Internal Server Error: /movie_api/searchMovieListWithPos/
Traceback (most recent call last):
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/movieapi.py", line 213, in SearchMovieListWithPos
    MovieCrawl(reqtheater)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/crawling.py", line 47, in MovieCrawl
    LotteCinemaCrawl(theaterObj)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/crawling.py", line 189, in LotteCinemaCrawl
    driver.get(url)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: headless chrome=78.0.3904.70)

[28/Oct/2019 14:32:35] "GET /movie_api/searchMovieListWithPos/?longitude=127.029248&latitude=37.511168 HTTP/1.1" 500 95189
Watching for file changes with StatReloader
Internal Server Error: /movie_api/searchMovieListWithPos/
Traceback (most recent call last):
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/movieapi.py", line 213, in SearchMovieListWithPos
    MovieCrawl(reqtheater)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/crawling.py", line 47, in MovieCrawl
    LotteCinemaCrawl(theaterObj)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/crawling.py", line 189, in LotteCinemaCrawl
    driver.get(url)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: headless chrome=78.0.3904.70)

[28/Oct/2019 14:32:55] "GET /movie_api/searchMovieListWithPos/?longitude=127.029248&latitude=37.511168 HTTP/1.1" 500 95192
Watching for file changes with StatReloader
